spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/practice
    user: postgres
    password: 1234
    baselineOnMigrate: true
    schemas: public
    clean-disabled: true
    locations: classpath:db/migration

